# GitLeaks configuration for Linux Automation System
# This configuration defines rules for detecting secrets in the repository

title = "Linux Automation System - Secret Detection"

[extend]
# Use default rules as baseline
useDefault = true

[[rules]]
id = "bash-admin-config-secrets"
description = "Bash Admin configuration files with potential secrets"
regex = '''(?i)(password|secret|key|token|credential)\s*[:=]\s*["']?[a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]{8,}["']?'''
path = '''config/.*\.(json|conf|cfg)$'''
tags = ["config", "secret"]

[[rules]]
id = "ssh-private-keys"
description = "SSH private keys"
regex = '''-----BEGIN [A-Z]+ PRIVATE KEY-----'''
tags = ["ssh", "private-key", "secret"]

[[rules]]
id = "database-connection-strings"
description = "Database connection strings"
regex = '''(?i)(mysql|postgres|mongodb|redis)://[a-zA-Z0-9_\-]+:[a-zA-Z0-9_\-]+@'''
tags = ["database", "connection-string", "secret"]

[[rules]]
id = "api-keys-generic"
description = "Generic API keys"
regex = '''(?i)(api[_\-]?key|apikey|auth[_\-]?token)\s*[:=]\s*["']?[a-zA-Z0-9!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]{16,}["']?'''
tags = ["api-key", "secret"]

[[rules]]
id = "hardcoded-passwords"
description = "Hardcoded passwords in scripts"
regex = '''(?i)(password|passwd|pwd)\s*[:=]\s*["'][^"']{4,}["']'''
path = '''.*\.(sh|bash|py)$'''
tags = ["password", "hardcoded", "secret"]

# Allowlist configuration
[allowlist]
paths = [
    ".git/",
    ".*\\.log$", 
    ".*\\.tmp$",
    "node_modules/",
    "vendor/",
    ".github/workflows/security.yml"
]

regexes = [
    # Documentation files
    '''README\.md|CHANGELOG\.md|docs/.*\.md''',
    # Example configuration files
    '''.*\.example$|.*\.template$|.*\.sample$''',
    # Test files with dummy data
    '''test.*|.*test.*|.*_test\..*''',
    # Known safe placeholder values
    '''(password|secret|key|token)\s*[:=]\s*["']?(your_|example_|placeholder_|dummy_|test_|sample_)''',
    # Empty or null values
    '''(password|secret|key|token)\s*[:=]\s*["']?(\s*|null|nil|none|empty|""|'')["']?''',
    # Environment variable references
    '''\$\{?[A-Z_]+\}?|\$[A-Z_]+''',
    # Configuration file comments and documentation
    '''^\s*#.*''',
    # Common non-secret patterns that might trigger false positives
    '''(?i)(version|release|build|commit|branch)[:=]\s*["']?[a-zA-Z0-9\-\.]+["']?''',
    '''(?i)(hostname|servername|domain)[:=]\s*["']?[a-zA-Z0-9\-\.]+["']?''',
    '''(?i)(username|user|account)[:=]\s*["']?[a-zA-Z0-9\-_]+["']?''',
    '''(?i)(path|directory|folder)[:=]\s*["']?[\/a-zA-Z0-9\-_\.]+["']?'''
]